### ISSUE TITLE
How do I set a section heading if its prefix is both the character it starts with?

### ISSUE THREAD

**Issue by desbest** [maegul/comment_marks#8]
How do I set a section heading if its prefix is both the character it starts with?

For example if I have a markdown file with the `.md` file extension.

```
# header 1
some text here

# header 2
some other text here

## header 2.1
this is for a subheader
```

Using your plugin, I can only find subheaders as a section to navigate through, as the subheader has 2 symbols whereas the top level header only has one.

So how can this be achieved?

**Comment by maegul** [comment]
Hi! Sorry, for some reason this slipped through the cracks. 

What you’re trying to do isn’t what the plug-in is for. If you want to navigate to a heading in markdown, you can use the goto symbol functionality in Sublime, provided the syntax is recognised.

If you want to navigate to a comment, which is what this plug-in is for, then you’d first need to create a comment in markdown (which will be the same as for HTML) and then write out a comment-mark inside that comment.

The advantage of doing this, even in a markdown file, if it isn’t clear, is that the comment won’t be visible in any rendering the markdown (eg HTML) but will still be available for navigation purposes. 

Hope that helps! This plug-in only works on comments.

**Comment by maegul** [comment]
Closing as I think I’ve answered the question which isn’t an issue with the plug-in but rather its scope
